/*
 * ADC_CONFIG.h
 *
 * Created: 4/11/2022 9:20:09 PM
 * Author: Mahmoud Sarhan
 * Email  : eng.mahmoud.adel94@gmail.com
 */ 


#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_


#define ADC_DDR								(DDRA)

#define ADC_MULTIPLEXER_SELECTION_REG		(ADMUX)


// ADC_MULTIPLEXER_SELECTION_REG BITS

#define REF_SELCTION_BIT_0					(REFS0)
#define REF_SELCTION_BIT_1					(REFS1)
#define ADC_LEFT_ADJUST_RESULT				(ADLAR)
#define ANALOG_CHANNEL_SELECTION_BIT_0		(MUX0)
#define ANALOG_CHANNEL_SELECTION_BIT_1		(MUX1)
#define ANALOG_CHANNEL_SELECTION_BIT_2		(MUX2)
#define ANALOG_CHANNEL_SELECTION_BIT_3		(MUX3)
#define ANALOG_CHANNEL_SELECTION_BIT_4		(MUX4)




#define ADC_CONTROL_AND_STATUS_A_REG		(ADCSRA)


// ADC_CONTROL_AND_STATUS_A_REG BITS

#define ADC_ENABLE							(ADEN)
#define ADC_START_CONVERSION				(ADSC)
#define ADC_AUTO_TRIGGER_ENABLE				(ADATE)
#define ADC_INTERRUPT_FLAG					(ADIF)
#define ADC_INTERRUPT_ENABLE				(ADIE)
#define ADC_PRESCALER_SELECTION_BIT_0		(ADPS0)
#define ADC_PRESCALER_SELECTION_BIT_1		(ADPS1)
#define ADC_PRESCALER_SELECTION_BIT_2		(ADPS2)



#define ADC_DATA_REG						(ADC)
#define ADC_DATA_H_REG						(ADCH)
#define ADC_DATA_L_REG						(ADCL)


#define SPECIAL_FUNCTION_REG				(SFIOR)

// SPECIAL_FUNCTION_REG BITS
#define ADC_AUTO_TRIGGER_SOURCE_BIT_0		(ADTS0)
#define ADC_AUTO_TRIGGER_SOURCE_BIT_1		(ADTS1)
#define ADC_AUTO_TRIGGER_SOURCE_BIT_2		(ADTS2)

// REF_SELECTION_MODES

typedef uint8_t REF_SELCTION_MODE;

#define AREF_INTERNAL_VREF_OFF				((REF_SELCTION_MODE)0U)
#define AVCC								((REF_SELCTION_MODE)1U)
#define RESERVED							((REF_SELCTION_MODE)2U)
#define INTERNAL_2_56V_REF					((REF_SELCTION_MODE)3U)


typedef uint8_t ANALOG_CHANNEL_MODE;

#define CHANNEL_0							((ANALOG_CHANNEL_MODE)0U)
#define CHANNEL_1							((ANALOG_CHANNEL_MODE)1U)
#define CHANNEL_2							((ANALOG_CHANNEL_MODE)2U)
#define CHANNEL_3							((ANALOG_CHANNEL_MODE)3U)
#define CHANNEL_4							((ANALOG_CHANNEL_MODE)4U)
#define CHANNEL_5							((ANALOG_CHANNEL_MODE)5U)
#define CHANNEL_6							((ANALOG_CHANNEL_MODE)6U)
#define CHANNEL_7							((ANALOG_CHANNEL_MODE)7U)



typedef uint8_t PRESCALER_MODES;

#define PRESCALER_2_0					((PRESCALER_MODES)0U)
#define PRESCALER_2						((PRESCALER_MODES)2U)
#define PRESCALER_4						((PRESCALER_MODES)4U)
#define PRESCALER_8						((PRESCALER_MODES)8U)
#define PRESCALER_16					((PRESCALER_MODES)16U)
#define PRESCALER_32					((PRESCALER_MODES)32U)
#define PRESCALER_64					((PRESCALER_MODES)64U)
#define PRESCALER_128					((PRESCALER_MODES)128U)



typedef uint8_t TRIGGER_SOURCE_MODES;

#define FREE_RUNNING_MODE				((TRIGGER_SOURCE_MODES)0U)
#define ANALOG_COMPARATOR				((TRIGGER_SOURCE_MODES)1U)
#define EXTERNAL_INTERRUPT_REQ			((TRIGGER_SOURCE_MODES)2U)
#define TIMER_0_COMPARE_MATCH			((TRIGGER_SOURCE_MODES)3U)
#define TIMER_0_OVERFLOW				((TRIGGER_SOURCE_MODES)4U)
#define TIMER_1_COMPARE_MATCH			((TRIGGER_SOURCE_MODES)5U)
#define TIMER_1_OVERFLOW_MATCH			((TRIGGER_SOURCE_MODES)6U)
#define TIMER_1_CAPTURE_MODE			((TRIGGER_SOURCE_MODES)7U)


#define ENABLE(x)						(1<<x)
#define INIT							(1U)
#define NOT_INIT						(0U)
#endif /* ADC_CONFIG_H_ */